name: mpmp
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - libiconv=1.16
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.1.3
  - python=3.7.9
  - pytest=6.2.1
  - scikit-learn=0.23.2
  - seaborn=0.11.0
  - svgutils=0.3.1
  - tqdm=4.54.1
  - umap-learn=0.4.6
  - pip:
    - venn==0.1.3

